// Device dimensions for App Store screenshots
export const deviceDimensions = {
  iphone16promax: { width: 1320, height: 2868 },
  iphone14plus: { width: 1284, height: 2778 },
  iphone16pro: { width: 1206, height: 2622 },
  iphone13pro: { width: 1170, height: 2532 },
  iphone8plus: { width: 1242, height: 2208 },
  iphonese3: { width: 750, height: 1334 },
  iphonese1: { width: 640, height: 1136 },
  ipadPro: { width: 2064, height: 2752 },
  androidPixel9Pro: { width: 1280, height: 2856 },
  androidTablet7: { width: 1200, height: 1920 },
  androidTablet10: { width: 1600, height: 2560 },
};

export const devicesIphone = {
  iphone16promax: "iPhone 16 Pro Max",
  iphone14plus: "iPhone 14 Plus",
  iphone16pro: "iPhone 16 Pro",
  iphone13pro: "iPhone 13 Pro",
  iphone8plus: "iPhone 8 Plus",
  iphonese3: "iPhone SE (3rd generation)",
  iphonese1: "iPhone SE (1st generation)",
};

export const devicesIpad = {
  ipadPro: "iPad Pro 13-inch (M4)",
};

export const devicesAndroidPhone = {
  androidPixel9Pro: "Pixel 9 Pro",
};

export const devicesAndroidTablet = {
  androidTablet7: "Nexus 7",
  androidTablet10: "Pixel Tablet",
};

export const deviceNames = {
  ...devicesIphone,
  ...devicesIpad,
  ...devicesAndroidPhone,
  ...devicesAndroidTablet,
};

export const deviceDisplaySizes = {
  iphone16promax: '6.9"',
  iphone14plus: '6.5"',
  iphone16pro: '6.3"',
  iphone13pro: '6.1"',
  iphone8plus: '5.5"',
  iphonese3: '4.7"',
  iphonese1: '4"',
  ipadPro: '13"',
  androidTablet7: '7"',
  androidTablet10: '10"',
};

export const defaultConfigs = {
  iphone16promax: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 493,
    textTopDistance: 234,
    deviceSizeFactor: 1.1,
    borderRadius: 50,
  },
  iphone14plus: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 493,
    textTopDistance: 234,
    deviceSizeFactor: 1.1,
    borderRadius: 50,
  },
  iphone16pro: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 493,
    textTopDistance: 234,
    deviceSizeFactor: 1.1,
    borderRadius: 50,
  },
  iphone13pro: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 493,
    textTopDistance: 234,
    deviceSizeFactor: 1.1,
    borderRadius: 50,
  },
  iphone8plus: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 493,
    textTopDistance: 234,
    deviceSizeFactor: 1,
    borderRadius: 30,
  },
  iphonese3: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 15,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 60,
    fontWeight: "500",
    bezelTopDistance: 307,
    textTopDistance: 148,
    deviceSizeFactor: 1,
    borderRadius: 30,
  },
  iphonese1: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 12,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 50,
    fontWeight: "500",
    bezelTopDistance: 272,
    textTopDistance: 138,
    deviceSizeFactor: 1,
    borderRadius: 13,
  },
  ipadPro: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 25,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 467,
    textTopDistance: 250,
    deviceSizeFactor: 1.1,
    borderRadius: 40,
  },
  androidPixel9Pro: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 493,
    textTopDistance: 234,
    deviceSizeFactor: 1.1,
    borderRadius: 50,
  },
  androidTablet7: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 421,
    textTopDistance: 206,
    deviceSizeFactor: 1.2,
    borderRadius: 50,
  },
  androidTablet10: {
    textColor: "#11181C",
    backgroundColor: "#dcf7fd",
    bezelWidth: 20,
    bezelColor: "#11181C",
    fontFamily: "Fredoka, sans-serif",
    fontSize: 100,
    fontWeight: "500",
    bezelTopDistance: 493,
    textTopDistance: 234,
    deviceSizeFactor: 1.1,
    borderRadius: 50,
  },
};
